### ISSUE TITLE
[antminer-monitor] Issue: Warning: Unable to obtain device information! 

### ISSUE THREAD

**Issue by ghoffman9** [stangri/openwrt_packages#104] opened 2020-06-09 11:30 UTC
**Describe the bug**
on mvebu (wrt1900ac v1):
Model	Linksys WRT1900AC v1
Architecture	ARMv7 Processor rev 2 (v7l)
Firmware Version	OpenWrt SNAPSHOT r13520-68b94f0fb4 / LuCI Master git-20.154.54590-05f07e5
Kernel Version	5.4.43

after upgrade to r13519 or r13520, the advanced-reboot feature gives the error:
Warning: Unable to obtain device information!
**To Reproduce**
1. reboot
2. reflash build
3. same error
4. tried upgrading opkg - current version gives same error
Package luci-app-advanced-reboot (git-20.113.70804-9d02ef1) installed in root is up to date.

**Expected behavior**

**Antminer Monitor run-time information**

1. Output of ```/etc/init.d/antminer-monitor start```:

   ```sh

   ```

**Comment by stangri** [comment] 2020-06-09 14:52
I was thrown off by the antminer-monitor title. There was a discussion of changing device names again, that's what probably happened, can you post the output of `cat /tmp/sysinfo/board_name`?

**Comment by stangri** [comment] 2020-06-09 19:26
Duplicate of [#4135](https://github.com/openwrt/luci/issues/4135).

**Closed as completed by stangri** 2020-06-09 19:26 UTC

**Comment by ghoffman9** [comment] 2020-06-10 10:47
thank you.
output of sysinfo/board_name:
linksys,wrt1900ac-v1
